### PR TITLE
(#74) correctly close game form

### LINKED ISSUE #74: Black square stays after exiting the game
1. Start the game using `Bloodmasters.Client` default configuration
2. It will start launcher
3. Use launcher to start the game
4. Play the game
5. Exit the game
6. You'll see a black square. Here, it is visible on top of the launcher window.

image

The game process is still alive at that moment.

Here's the parallel stacks window in case that helps:
image

It looks like there's an outstanding call to `SynchronizationContext.Send` somewhere that gets stuck and blocks the runtime from terminating.

### PR DESCRIPTION
**Pull request by KeterSCP**
Fixes #74

### CODE REVIEW

**Comment by KeterSCP** [comment]
I don't get it. Why changes from force push do not appear in the diffs?

**Comment by ForNeVeR** [comment]
It looks like we've just found a bug. I can see that you've replaced `OnClosing` by `OnFormClosing` in two places, and yet the diff in PR only shows one place. That is… unusual.

**Comment by ForNeVeR** [comment]
[Reported to GitHub](https://github.com/orgs/community/discussions/61985).

**Review by ForNeVeR — APPROVED** [review]
And thanks for your contribution!

**Comment by ForNeVeR** [comment]
Ha, it didn't even properly register as merged. I'm closing it manually. Added this information into my bug report.

**Comment by ForNeVeR** [comment]
Hey, look, the PR has been healed by itself. It now shows the correct content.

**Pull request closed without merging**
