### PR TITLE
(#28) Enable high dpi by default

### LINKED ISSUE #28: Launcher: wrong layout on HiDPI
1. Start the Bloodmasters project (Note: **this is not the launcher**, this is the game itself).
2. It will start the launcher process in some unusual mode (HiDPI override?) which
   - is drawn much more crispy than the default run mode. See this image: old on the right, new on the left
     image
   - has several layout glitches:
     image
     image

We'll need to figure out why does it has different DPI modes when started directly from the IDE or from the game process, and fix the hidpi layouting issue (and maybe just make it work in HiDPI always).

### PR DESCRIPTION
**Pull request by KeterSCP**
- Fix layout with high dpi
- Don't resize controls programmatically, use docking and panels instead

When I opened VS winforms designer and unlocked controls, the FormMain code was automatically regenerated by the designer, so the majority of changes in that file are autogenerated.

This depends on https://github.com/ForNeVeR/bloodmasters/pull/52, will rebase after merge

Fix #28

### CODE REVIEW

**Review by ForNeVeR — APPROVED** [review]
The changes LGTM so far, but I'll check the layout after rebase.

**Comment by ForNeVeR** [comment]
So, we've got a BOM in a `.csproj` file. Any idea how it got there? I can relax the restrictions on project files if some automatic tool does that and has no corresponding settings.

**Comment by KeterSCP** [comment]
I have no idea how BOM got there. AFAIR I changed indenting in .csproj via Rider interface

**Comment by ForNeVeR** [comment]
Ok, so this doesn't fix any issues (I still see #28 in this branch), but updates the form file and enables the hi-dpi layout everywhere. LGTM!

**Comment by ForNeVeR** [comment]
But wait, it was supposed to fix #28, right?

**Comment by KeterSCP** [comment]
Yep, what issues exactly do you see on this branch?

**Comment by ForNeVeR** [comment]
Hmmm, I see no issues after restarting it for several times.

Could it be that it was serializing the wrong layout somewhere and then reading it from a file?

**Comment by ForNeVeR** [comment]
Whatever, let's merge!

**Pull request merged**
